---
- hosts: localhost
  become: yes
  pre_tasks:
    - name: set fact
      set_fact:
        foo: [foobar, and, hello, world]

    - name: display debug
      debug:
        msg: "{{item}} - ansible_os_family: {{ansible_os_family}}, {{ansible_distribution}}"
      when: ansible_os_family == "RedHat"
      with_items: "{{foo}}"

    - name: Uninstall the used MySQL repo.
      yum:
        name: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
        state: absent

    - name: Install the MySQL repo.
      yum:
        name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
        state: absent

    - name: upgrade all packages
      yum: name=* state=latest
  
    - name: Override variables for MySQL (RedHat).
      set_fact:
        mysql_daemon: mysqld
        mysql_packages: ['mysql-server']
        mysql_log_error: /var/log/mysqld.err
        mysql_syslog_tag: mysqld
        mysql_pid_file: /var/run/mysqld/mysqld.pid
        mysql_socket: /var/lib/mysql/mysql.sock

    - name: display debug
      debug:
        msg: "{{authentication_ldap_simple_user_search_attr}}"
